[build]
build-std = false

[build.env]
passthrough = [
  "AWS_LC_NO_PREFIX",
  "CROSS_DOCKER_IN_DOCKER",
  "AWS_LC_SYS_CFLAGS",
  "AWS_LC_SYS_STATIC",
  "RUSTFLAGS"
]

[target.mips-unknown-linux-gnu]
build-std = true

[target.mips-unknown-linux-musl]
build-std = ["std", "panic_abort"]
image = "ghcr.io/cross-rs/mips-unknown-linux-musl:edge"

[target.mipsel-unknown-linux-musl]
build-std = true
image = "ghcr.io/cross-rs/mipsel-unknown-linux-musl:edge"

[target.mips64-unknown-linux-muslabi64]
build-std = true
image = "ghcr.io/cross-rs/mips64-unknown-linux-muslabi64:edge"

[target.mips64el-unknown-linux-muslabi64]
build-std = true
image = "ghcr.io/cross-rs/mips64el-unknown-linux-muslabi64:edge"
